{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'AIzaSyC0ssQGBFXXFtO4eN7sqHJywGj_CBPw0qM'"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from dotenv import load_dotenv\n",
    "import os\n",
    "load_dotenv()  # this for env file if you created \n",
    "\n",
    "\n",
    "# set GOOGLE_API_KEY=\"\"\n",
    "os.environ[\"GOOGLE_API_KEY\"]=\"AIzaSyC0ssQGBFXXFtO4eN7sqHJywGj_CBPw0qM\"\n",
    "os.environ[\"GOOGLE_API_KEY\"]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'GOOGLE_API_KEY'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mos\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[43mos\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43menviron\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mGOOGLE_API_KEY\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "File \u001b[1;32md:\\study\\Multilingual_AI_Voice_Assistance\\venv\\lib\\os.py:679\u001b[0m, in \u001b[0;36m_Environ.__getitem__\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m    676\u001b[0m     value \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_data[\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mencodekey(key)]\n\u001b[0;32m    677\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m:\n\u001b[0;32m    678\u001b[0m     \u001b[38;5;66;03m# raise KeyError with the original key value\u001b[39;00m\n\u001b[1;32m--> 679\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m(key) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    680\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdecodevalue(value)\n",
      "\u001b[1;31mKeyError\u001b[0m: 'GOOGLE_API_KEY'"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ[\"GOOGLE_API_KEY\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "import google.generativeai as genai\n",
    "\n",
    "#configure the apis\n",
    "genai.configure()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "model = genai.GenerativeModel('gemini-pro')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'In the twilight\\'s embrace, as the world surrendered to slumber, I found myself trapped in a labyrinth of my own mind. Sleep eluded me, and my thoughts spiraled into a realm of unfathomable hallucinations.\\n\\nI lay in my bed, my body still, but my mind raced like a wild mustang. The room began to warp and distort, its edges blurring into an abyss. Suddenly, the walls seemed to close in on me, suffocating me with their oppressive presence.\\n\\nFrom the darkness emerged a shadowy figure. Its form was indistinct, its features obscured by a swirling mist. It glided towards me, its movements fluid and unnatural. As it drew closer, I felt a surge of terror wash over me.\\n\\nThe figure\\'s voice was a mere whisper, yet it cut through the silence like a knife. \"Do you fear me?\" it hissed.\\n\\nI gasped and tried to speak, but my voice was lost in the depths of my own hallucinations. The figure reached out a skeletal hand, its icy fingers brushing against my skin. I shuddered with revulsion and tried to push it away, but my body refused to obey.\\n\\nSuddenly, the room transformed into a desolate wasteland. The walls crumbled into dust, and the floor became a barren expanse. The shadowy figure stood before me, its form now towering over mine.\\n\\n\"You cannot escape me,\" it whispered. \"I am the darkness that dwells within you.\"\\n\\nI screamed, but my voice was swallowed by the void. The figure lunged at me, its claws extended. I tried to flee, but my legs were heavy as lead. In a moment of despair, I realized that I was trapped in a never-ending nightmare.\\n\\nAs the darkness envelops me, I felt my sanity slipping away. The hallucinations became more vivid, more terrifying. I saw grotesque creatures that haunted my dreams and heard whispers that drove me to the brink of madness.\\n\\nTime seemed to lose all meaning as the endless night stretched into an eternity. I was lost in a realm where reality and delusion intertwined, where shadows whispered secrets and the darkness consumed all.'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.generate_content(\"write hallunication story\").text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
